import gradio as gr
import google.generativeai as genai
import os
from PIL import Image

def analyze_ecg(image, progress=gr.Progress()):
    if not image:
        return "Please upload an ECG image."
    
    progress(0.1, desc="Configuring API...")
    
    # Get API key from environment variable (set in Hugging Face Spaces secrets)
    api_key = os.getenv("GEMINI_API_KEY")
    
    if not api_key:
        return "Error: API key not configured. Please set GEMINI_API_KEY environment variable."
            
    try:
        genai.configure(api_key=api_key)
        
        # we will use gemini-2.5-flash since it handles multimodality well and is supported by this API key.
        model = genai.GenerativeModel('gemini-2.5-flash')
        
        prompt = """
        You are an expert cardiologist and medical assistant. I am providing you with an image of an ECG (Electrocardiogram) signal.
        Please analyze this ECG image to the best of your ability and provide a structured response with the following sections:
        
        1. **Suggestion:** State clearly if the ECG appears "Normal" or "Abnormal". If abnormal, specify the potential finding.
        2. **Analysis:** Provide a brief reasoning based on the visible waveforms (such as P wave, QRS complex, T wave, ST segment).
        3. **What to Do:** Give immediate recommendations based on these findings.
        4. **First Aid:** Outline any relevant first aid steps if the condition indicates a critical situation.
        
        **Important Disclaimer:** Always add a disclaimer at the end stating that this analysis is generated by an AI model for educational/informational purposes only and should not replace professional medical diagnosis, advice, or treatment.
        """
        
        progress(0.6, desc="Analyzing ECG with Gemini AI (this may take a few seconds)...")
        response = model.generate_content([prompt, image])
        
        progress(1.0, desc="Analysis complete!")
        return response.text
    except Exception as e:
        return f"An error occurred during analysis: {str(e)}"

with gr.Blocks(title="ECG Signal Analyzer", theme=gr.themes.Soft()) as demo:
    gr.Markdown("#  ECG Signal Analyzer")
    gr.Markdown("Upload an image of an ECG signal to get an assessment (Normal/Abnormal), reasoning, and immediate first aid suggestions using the Google Gemini AI.")
    
    with gr.Row():
        with gr.Column():
            image_input = gr.Image(type="pil", label="Upload ECG Image")
            analyze_button = gr.Button("Analyze ECG", variant="primary")
            
        with gr.Column():
            text_output = gr.Markdown(label="Analysis Results")
            
    analyze_button.click(
        fn=analyze_ecg, 
        inputs=[image_input], 
        outputs=text_output
    )

if __name__ == "__main__":
    demo.launch()
